<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-07 at 06:01:43.
 */
include_once '../Area.php';
include_once '../AreaHandler.php';
class AreaHandlerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AreaHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AreaHandler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ("1") == true.
     *
     * @covers AreaHandler::addArea
     */
    public function testAddArea() {
        $this->assertEquals(
                true
                , $this->object->addArea("1")
        );
    }

    /**
     * Generated from @assert ("2") == true.
     *
     * @covers AreaHandler::addArea
     */
    public function testAddArea2() {
        $this->assertEquals(
                true
                , $this->object->addArea("2")
        );
    }

    /**
     * Generated from @assert (null) == false.
     *
     * @covers AreaHandler::addArea
     */
    public function testAddArea3() {
        $this->assertEquals(
                false
                , $this->object->addArea(null)
        );
    }

}
