<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-07 at 04:33:40.
 */
include_once './messageSend.php';
class messageSendTest extends PHPUnit_Framework_TestCase {

    /**
     * @var messageSend
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new messageSend;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ("1") == true.
     *
     * @covers messageSend::compose_and_send_message
     */
    public function testCompose_and_send_message() {
        $this->assertEquals(
                true
                , $this->object->compose_and_send_message("1")
        );
    }

    /**
     * Generated from @assert ("All") == true.
     *
     * @covers messageSend::compose_and_send_message
     */
    public function testCompose_and_send_message2() {
        $this->assertEquals(
                true
                , $this->object->compose_and_send_message("All")
        );
    }

    /**
     * Generated from @assert ("asd") == false.
     *
     * @covers messageSend::compose_and_send_message
     */
    public function testCompose_and_send_message3() {
        $this->assertEquals(
                false
                , $this->object->compose_and_send_message("asd")
        );
    }

    /**
     * Generated from @assert ("Alpha") == true.
     *
     * @covers messageSend::compose_and_send_message
     */
    public function testCompose_and_send_message4() {
        $this->assertEquals(
                true
                , $this->object->compose_and_send_message("Alpha")
        );
    }

    /**
     * Generated from @assert ("1") == true.
     *
     * @covers messageSend::retreive_last_position
     */
    public function testRetreive_last_position() {
        $this->assertEquals(
                true
                , $this->object->retreive_last_position("1")
        );
    }

    /**
     * Generated from @assert (null) == false.
     *
     * @covers messageSend::retreive_last_position
     */
    public function testRetreive_last_position2() {
        $this->assertEquals(
                false
                , $this->object->retreive_last_position(null)
        );
    }

}
