<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-07 at 04:27:26.
 */
include_once 'messageReceive.php';
class messageReceiveTest extends PHPUnit_Framework_TestCase {

    /**
     * @var messageReceive
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new messageReceive;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ('{"user":"2","lat":"42.116296999999996","lng":"-80.0362004"}') == true.
     *
     * @covers messageReceive::receive_message
     */
    public function testReceive_message() {
        $this->assertEquals(
                true
                , $this->object->receive_message('{"user":"2","lat":"42.116296999999996","lng":"-80.0362004"}')
        );
    }

    /**
     * Generated from @assert ('{"user":"","lat":"42.116296999999996","lng":"-80.0362004"}') == true.
     *
     * @covers messageReceive::receive_message
     */
    public function testReceive_message2() {
        $this->assertEquals(
                true
                , $this->object->receive_message('{"user":"","lat":"42.116296999999996","lng":"-80.0362004"}')
        );
    }

    /**
     * Generated from @assert ('{"user":"2","lat":"","lng":"-80.0362004"}') == true.
     *
     * @covers messageReceive::receive_message
     */
    public function testReceive_message3() {
        $this->assertEquals(
                true
                , $this->object->receive_message('{"user":"2","lat":"","lng":"-80.0362004"}')
        );
    }

    /**
     * Generated from @assert ('{"user":"2","lat":"42.116296999999996","lng":""}') == true.
     *
     * @covers messageReceive::receive_message
     */
    public function testReceive_message4() {
        $this->assertEquals(
                true
                , $this->object->receive_message('{"user":"2","lat":"42.116296999999996","lng":""}')
        );
    }

    /**
     * @covers messageReceive::store_point
     * @todo   Implement testStore_point().
     */
    public function testStore_point() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
