<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-07 at 04:56:26.
 */
include_once '../WeatherHandler.php';
class WeatherHandlerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var WeatherHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WeatherHandler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ("F") > 0.
     *
     * @covers WeatherHandler::getTemperature
     */
    public function testGetTemperature() {
        $this->assertGreaterThan(
                0
                , $this->object->getTemperature("F")
        );
    }

    /**
     * Generated from @assert ("C") > 0.
     *
     * @covers WeatherHandler::getTemperature
     */
    public function testGetTemperature2() {
        $this->assertGreaterThan(
                0
                , $this->object->getTemperature("C")
        );
    }

    /**
     * Generated from @assert ("ASD") == ErrorException.
     *
     * @covers WeatherHandler::getTemperature
     */
    public function testGetTemperature3() {
        $this->assertEquals(
                ErrorException
                , $this->object->getTemperature("ASD")
        );
    }

    /**
     * Generated from @assert () > 0.
     *
     * @covers WeatherHandler::getHumidity
     */
    public function testGetHumidity() {
        $this->assertGreaterThan(
                0
                , $this->object->getHumidity()
        );
    }

    /**
     * Generated from @assert () > 0.
     *
     * @covers WeatherHandler::getPrecipitation
     */
    public function testGetPrecipitation() {
        $this->assertGreaterThan(
                0
                , $this->object->getPrecipitation()
        );
    }

    /**
     * Generated from @assert () > 0.
     *
     * @covers WeatherHandler::getWindSpeed
     */
    public function testGetWindSpeed() {
        $this->assertGreaterThan(
                0
                , $this->object->getWindSpeed()
        );
    }

    /**
     * Generated from @assert () > 0.
     *
     * @covers WeatherHandler::getWindDirection
     */
    public function testGetWindDirection() {
        $this->assertGreaterThan(
                0
                , $this->object->getWindDirection()
        );
    }

    /**
     * @covers WeatherHandler::updateWeatherObject
     * @todo   Implement testUpdateWeatherObject().
     */
    public function testUpdateWeatherObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
